version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: delimo-backend
    container_name: delimo-backend
    ports:
      - "192.168.0.18:8080:8080"  # Bind backend to 192.168.0.18
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/delimo
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.1
    container_name: delimo-db
    ports:
      - "192.168.0.18:5432:5432"  # Bind database to 192.168.0.18
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=delimo
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "delimo", "-U", "dbuser"]
      timeout: 5s
      interval: 5s
      retries: 10

  frontend:
    build:
      context: frontend/delimo
      dockerfile: Dockerfile
    image: frontend
    container_name: delimo-frontend
    ports:
      - "192.168.0.18:80:80"  # Bind frontend to 192.168.0.18
    depends_on:
      - backend
