services:
  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - JWT_SECRET=Y2B7y+7pKiUVuZW8xB2mM8E5Om3z3yTCghHVcWpkKHk=
      - HOST_NAME=db
    ports:
      - "8080:8080"
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=delimo
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10