@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

Person(user, "Конечный пользователь")
System(system, "Delimo Application", "Spring Boot Modulith")

Container(system_app, "Backend (Spring Boot)", "Java 21, Spring Modulith", "API для фронтенда и модулей")
Container_Db(db, "PostgreSQL", "Реляционная БД", "Данные пользователей, заявок, предметов")
Container_MinIO(minio, "MinIO", "Объектное хранилище", "Хранение изображений")

Rel(user, system_app, "HTTP/HTTPS")
Rel(system_app, db,       "JDBC")
Rel(system_app, minio,    "S3 API")

Container_Boundary(system_app, "Модули приложения") {
  Component(email, "Email Module",    "Уведомления и фидбэк")
  Component(userM, "User Module",     "Регистрация и профиль")
  Component(sec,   "Security Module", "JWT, OAuth2, Spring Security")
  Component(req,   "Request Module",  "Управление заявками")
  Component(item,  "Item Module",     "CRUD предметов, картинки")
}

Rel(email, db,  "JPA")
Rel(userM, db,  "JPA")
Rel(sec,   userM,"Проверка прав")
Rel(req,   db,  "JPA")
Rel(item,  minio, "S3 API / локальное хранение")
@enduml
