server:
  port: 8080
  servlet:
    context-path: /api

spring:
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration
  docker:
    compose:
      enabled: false
  application:
    name: delimo
  config:
    import: optional:classpath:.env[.properties]
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${HOST_NAME}:5432/delimo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Europe/Belgrade
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
  mail:
    host: mailcluster.loopia.se
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    root: info

app:
  frontend-url: ${UI_URL}
  jwt:
    secret: ${JWT_SECRET}

aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT}
    region:   ${AWS_S3_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    bucket:   ${AWS_S3_BUCKET}
    public-url: https://s3.delimo.rs
