server:
  servlet:
    context-path: /api

spring:
  application:
    name: delimo
  config:
    import: optional:classpath:.env[.properties]
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/delimo
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Europe/Belgrade
    date-format: yyyy-MM-dd HH:mm:ss
  security:
    user:
      name: admin
      password: 12345
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    protocol: smtp

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    root: "info"

imgbb:
  key: ${IMGBB_KEY}
