name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java and Maven
      - name: Set up JDK 21 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Build the Spring Boot backend
      - name: Build Spring Boot backend
        run: |
          cd backend
          chmod +x mvnw  # Ensure mvnw is executable
          ./mvnw clean package -DskipTests

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Vue.js frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          docker build -t valeriilinden/delimo-frontend:prod ./frontend/delimo
          docker push valeriilinden/delimo-frontend:prod

      # Build and push Spring Boot backend Docker image
      - name: Build and push backend Docker image
        run: |
          docker build -t valeriilinden/delimo-backend:prod --build-arg JAR_FILE=target/*.jar ./backend
          docker push valeriilinden/delimo-backend:prod
